### ISSUE TITLE
Having issue suppressing credential scanner results with .gdnsuppress file

### ISSUE THREAD

**Issue by DevOpsAzurance** [microsoft/security-devops-azdevops#110]
I am setting the task as follows:

 ```
 - task: MicrosoftSecurityDevOps@1
    displayName: Run MS Security DevOps
    inputs:
      command: 'run'
      policy: 'microsoft'
      break: true
      artifactName: 'CodeAnalysisLogs'
    ${{ if or(ne(parameters.SuppressionPaths, ''), ne(parameters.SuppressionPlaceholders, '')) }}:
      env:
        GDN_RUN_SUPPRESSIONFILE: MSDOSuppressionFile
```

I am creating the .gdn/MSDOSuppressionFile.gdnsuppression file with the following data:

```
{
    "tool": "Credential Scanner",
    "suppressions": [
        {
            "file": [
				"$(Build.SourcesDirectory)/src/main.ts",
				"$(Build.SourcesDirectory)/src/test.ts"
            ],
            "_justification": "False positive files"
        },
        {
            "placeholder": [
				"'client_secret': x.mrdhApicCSec,",
				"'Some-Secret': x.mrdhApicXIBMCSec,",
				"'Some-Client-Secret': x.deregApicXIBMCSec,",
				"'Some-Client-Secret': x.mozartApicXIBMCSec"
            ],
            "_justification": "False positive lines"
        },
        {
            "hash": [
				"9F0Kuc6b47nAOIqDqhEFct82R5oR+bP1+CcIwZlrRuI=",
				"test"
            ],
            "_justification": "False positive hashes"
        }
    ]
}
```

I have slowly expanded from its original which only had the "file" object. Since it was not working, I kept expanding to figure out what worked so I then added placeholders and then hashes. 

Currently I am getting:

```
Suppression Files: MSDOSuppressionFile
...
##[error]3. Credential Scanner Error CSCAN-GENERAL0130 - File: src/test.ts:src/test.ts. Line: 70. Column 29. 
    Signature: 94538d51b97d725caf27deaa18b50e2b5fa257d8008b1dcc49be508c2af846db
    Tool: Credential Scanner: Rule: CSCAN-GENERAL0130 (Client Secret / Api Key). https://aka.ms/CredScanDocs
    A potential secret was detected. Validate file contains secrets, remove, rotate credential, and use approved store. For additional information on secret remediation see the remediation section at https://aka.ms/CredScanDocs 
```
I have tried multiple ways to set the path for the files to be suppressed, in case I was setting the files wrong, but those two files keep getting picked up; test.ts and main.ts.  

Not sure where the suppression is failing and how.
