### ISSUE TITLE
Microsoft Security Devops Issue(MicrosoftSecurityDevOps@1)

### ISSUE THREAD

**Issue by NagendraKumarrao** [microsoft/security-devops-azdevops#111]
While i am implementing the task MicrosoftSecurityDevOps@1,
I am getting below error :

##[error]NullReferenceException: Object reference not set to an instance of an object.
##[error]MSDO CLI exited with an error exit code: 1.

Suddenly i am getting this error from today onwards.
Please anyone suggest me on this.

**Comment by babicahmed** [comment]
Experiencing the same issue with extension version 1.12.1 which was released last Thursday.

Current workaround is to run previous version(s) such as:
- task: MicrosoftSecurityDevOps@1.11.2

**Comment by NagendraKumarrao** [comment]
I am having doubt here that where i need to mention the MicrosoftSecurityDevOps@1.11.2 in YML file.
Please suggest me any example for YML.

**Comment by nesterenes** [comment]
I've run into this same error on a recent build (which was previously working). It seems that the `templateanalyzer` is the culprit. Works correctly when removing it from the input > tools.
Failure
```
- task: MicrosoftSecurityDevOps@1
  displayName: 'Microsoft Security DevOps'
  inputs:
    tools: 'antimalware,templateanalyzer'
```
Success
```
- task: MicrosoftSecurityDevOps@1
  displayName: 'Microsoft Security DevOps'
  inputs:
    tools: 'antimalware'
```
