### ISSUE TITLE
PackagesNotProvidedException when using .gdnconfig in ADO Pipeline with templates

### ISSUE THREAD

**Issue by aavdberg** [microsoft/security-devops-azdevops#123]
When I add the task:

```
  - task: MicrosoftSecurityDevOps@1
    displayName: 'Microsoft Security DevOps Scan'
    inputs:
      config: "pipelines/${{parameters.templateFolder}}/.defender/.gdnconfig"
```

in my pipeline template I am getting the following error: PackagesNotProvidedException

The folder structure is

``` mermaid
graph TD;
    R[Root] --> E[pipelines] --> E1[Landingzones] --> E1a[datamanagement]
    R --> G[source] --> G1[bicep] --> G1a[Landingzones] --> G1a1[datamanagement]
    E1a --> H[.defender] --> H1[.gdnconfig]
```

And this is how the .gdnconfig file looks:

```
{
  "scan": {
    "include": [
      "pipelines/landingzones/datamanagement/",
      "source/bicep/landingzones/datamanagement/"
    ]
  },
  "tools": {
    "bandit": {
      "enabled": true
    },
    "binskim": {
      "enabled": true
    },
    "checkov": {
      "enabled": true
    },
    "eslint": {
      "enabled": false
    },
    "templateanalyzer": {
      "enabled": true
    },
    "terrascan": {
      "enabled": false
    },
    "trivy": {
      "enabled": true
    }
  }
}
```
