### ISSUE TITLE
Bicep Repository Scans Failing in Checkov, IaC File Scanner, and Template Analyzer

### ISSUE THREAD

**Issue by weekendclimber** [microsoft/security-devops-azdevops#137]
I'm having issues with the task running in my environment. I've got Bicep files that I would like to have scanned, but it seems that the IaC category scanners all fail in various modes.

In my pipeline I have the following:

```
- task: MicrosoftSecurityDevOps@1
  displayName: "Run Microsoft Security Scan"
  inputs:
    policy: 'azuredevops'
    categories: 'IaC'
    publish: false
    artifactName: 'CodeAnalysisLogs'
```

It appears that Microsoft Defender for Cloud picks up the runs, unless I don't understand the dashboard in Azure fully. Not sure what is failing within the task. I believe this is running within a container, which is not publicly available like the task code is on GitHub. Otherwise, I would dig in and see what is going on with it.

See screenshots below.

Microsoft Defender for Cloud Dashboard:
![Image](https://github.com/user-attachments/assets/b024827d-c42e-4e92-be3a-0d01684c1b26)

Checkov Results:
![Image](https://github.com/user-attachments/assets/a0250552-3b07-4294-b1ae-99822f5132ef)

IaC File Scanner Results:
![Image](https://github.com/user-attachments/assets/b691c3f0-7b9e-4777-be04-a0d089faa135)

Template Analyzer Results:
![Image](https://github.com/user-attachments/assets/00f805b2-e0bc-4066-bfc3-0a1c431595e0)

Final Results:
![Image](https://github.com/user-attachments/assets/2e20259a-73fa-4938-a298-ae091de3f99a)

Raw Task Log:
[rawlog.txt](https://github.com/user-attachments/files/20957518/rawlog.txt)
