### ISSUE TITLE
Bandit and BinSkim cause errors

### ISSUE THREAD

**Issue by pim-simons** [microsoft/security-devops-azdevops#15]
Both Bandit and BinSkim are listed [here](https://github.com/microsoft/security-devops-azdevops#open-source-tools) as available tools.
However when I run extension with this config:
``` yaml
- task: MicrosoftSecurityDevOps@1
  displayName: 'Run Microsoft Defender for DevOps'
  inputs:
    tools: bandit
``` 
The run fails with:
##[error]bandit is missing required argument: Target
##[error]Error running bandit job: 1 of 1
##[error]AnalyzerMissingRequiredArgumentsException: bandit is missing one or more required arguments.

Same for BinSkim, if I run it like this:
``` yaml
- task: MicrosoftSecurityDevOps@1
  displayName: 'Run Microsoft Defender for DevOps'
  inputs:
    tools: binskim
``` 
The run fails with:
##[error]Error running binskim job: 1 of 1
##[error]InvalidResponseFileContentsException: Cannot create a response file with zero arguments. Ensure that your arguments are correctly set up.

Also when I run the task without specifying a tool (in which case all tools should be executed), bandit and binskim are missing:
```
Applicable Tools:
Tool Name: credscan
Tool Version: 2.5.0.5
Tool Config File Path: D:\a\1\s\.gdn\c\credscan.gdntool

Tool Name: eslint
Tool Version: 7.32.0.2
Tool Config File Path: D:\a\1\s\.gdn\c\eslint.gdntool

Tool Name: templateanalyzer
Tool Version: 0.3.1
Tool Config File Path: D:\a\1\s\.gdn\c\templateanalyzer.gdntool

Tool Name: terrascan
Tool Version: 1.14.0.1
Tool Config File Path: D:\a\1\s\.gdn\c\terrascan.gdntool

Tool Name: trivy
Tool Version: 0.19.2.1
Tool Config File Path: D:\a\1\s\.gdn\c\trivy.gdntool
```

Are Bandit and BinSkim supported or not?

**Comment by nb-atudose** [comment]
I encounter a similar issue. I receive this error:
```##[error]GuardianErrorExitCodeException: binskim completed with an Error exit code: 1. BinSkim failed. Verify the target(s) to be scanned. BinSkim targets must be a specific filename, or a pattern with a wildcard like *.dll, dir\*.dll, or dir\*```
How can I specify the binskim targets to the MicrosoftSecurityDevOps task?

**Comment by nb-atudose** [comment]
Found the solution in another GitHub issue. I added the .gdnconfig file with the content below to the project and it worked.
```
{
  "tools": [
    {
      "tool": {
        "name": "BinSkim",
        "version": "Latest"
      },
      "arguments": {
        "IgnorePdbLoadError": "true"
      }
    }
  ]
}
```
and in the pipeline file:
```
- task: MicrosoftSecurityDevOps@1
  displayName: 'Microsoft Security DevOps'
  inputs:
    config: 'gdnconfig/.gdnconfig'
    break: true
    tools: 'binskim'
```
