### ISSUE TITLE
Default for tools is not accurate

### ISSUE THREAD

**Issue by JFolberth** [microsoft/security-devops-azdevops#24]
When passing in the list of tools as ',' delaminated string "template-analyzer" is not recognized. Below is what I have and it fails:

```
parameters:
- name: config
  type: string
  default: '*.gdconfig'
- name: categories
  type: string
  default: 'all'
- name: languages
  type: string
  default: 'all'
- name: tools
  type: string
  default: 'bandit, binskim, eslint, template-analyzer, terrascan, trivy'
- name: break
  type: boolean
  default: false

steps:
- task: MicrosoftSecurityDevOps@1
  inputs:
    categories: ${{parameters.categories}}
    languages: ${{parameters.languages}}
    tools: ${{parameters.tools}}
    break: ${{parameters.break}}
```

When I remove the 'tools' argument it works.
