### ISSUE TITLE
No Malware Scan Options

### ISSUE THREAD

**Issue by johni-aveva** [microsoft/security-devops-azdevops#27]
As part of [Microsoft Security Code Analysis](https://learn.microsoft.com/en-us/azure/security/develop/security-code-analysis-overview),  AntiMalware Scanner Task is retired.

```
    - task: AntiMalware@3
      displayName: 'AntiMalware Scan'
      inputs:
        FileDirPath: '$(Build.ArtifactStagingDirectory)'
```

The [Microsoft Security DevOps for Azure DevOps](https://marketplace.visualstudio.com/items?itemName=ms-securitydevops.microsoft-security-devops-azdevops) ADO Marketplace listing includes `AntiMalware` in its list of tags; however, I haven't found any options or documentation that launches an antimalware scan.

Could you point me to guidance on executing an antimalware scan with this extension or another supported option for a malware scan?

**Comment by magic2** [comment]
```
- task: MicrosoftSecurityDevOps@1
  inputs:
    command: run
    break: true
    tools: AntiMalware, bandit, binskim, eslint, templateanalyzer, terrascan, trivy
    publish: false
```
