### ISSUE TITLE
Publish Terrascan and Credscan result in the ADO pipeline

### ISSUE THREAD

**Issue by aakanshaverma1310** [microsoft/security-devops-azdevops#30]
Is it possible to publish results for both Terrascan and CredScan in ADO Pipeline (PFB image)
I'm using below -
```
      - task: MicrosoftSecurityDevOps@1
        displayName: Credential Scanner- CredScan
        inputs:
          categories: 'secrets, code, artifacts, IaC, containers'
          tools: 'Credscan'

      - task: MicrosoftSecurityDevOps@1
        displayName: Credential Scanner- Terrascan
        inputs:
          categories: 'secrets, code, artifacts, IaC, containers'
          tools: 'terrascan'
```

![image](https://user-images.githubusercontent.com/45385925/216919020-de5829c6-fdbd-4c6b-b5d8-e356fb822fb4.png)
