### ISSUE TITLE
Global Exclusion/Suppression File Support/Format

### ISSUE THREAD

**Issue by joelmusheno** [microsoft/security-devops-azdevops#40]
I'm using:

```
    - task: MicrosoftSecurityDevOps@1
      displayName: 'Secrets scanning with Microsoft Security DevOps'
      inputs:
        categories: 'secrets'
        break: true
```

I'd like to establish a baseline without halting my build. 

I know i could simply turn `break: false` but I'm trying to stop any contributors from including. I'd like to follow the pattern that static analysis does with with a suppression file (like GlobalSuppressions.cs for static code analysis). 

I can't find any documentation on suppression lists/files, the only docs I can find point me to comments in line:
`#[SuppressMessage("Microsoft.Security", "CS002:SecretInNextLine")]` or `#[SuppressMessage("Microsoft.Security", "CS002:SecretInLine")]`

I have a few issues
1. It's bad form to include // or /**/ in json files (of which we have many)
2. I have false positives on a binary file, in which I can't write a comment

Does anyone have a way to specify files/lines to ignore outside of in-line comments?
