### ISSUE TITLE
Build not failing even if there are some bugs detected

### ISSUE THREAD

**Issue by raswinraaj** [microsoft/security-devops-azdevops#58]
I have the task setup for credscan, the tool has detected that there is a High Severity bug and the Scans tab shows it as bugs.
However it is not failing the build. Is there anything that I have to add to make the build fail ?
```
- task: MicrosoftSecurityDevOps@1
  displayName: 'Scan for Secrets in the repo'
  inputs:
    categories: 'secrets'
```
![image](https://github.com/microsoft/security-devops-azdevops/assets/50330414/d90c131f-9f1f-4817-996c-ae49a6a07e72)

Similar case for terrascan as well

```
- task: MicrosoftSecurityDevOps@1
  displayName: 'Microsoft Security DevOps scan'
  inputs:
    categories: 'Iac'

```
![image](https://github.com/microsoft/security-devops-azdevops/assets/50330414/6376c01b-b251-43d8-923a-df46d9dc841b)
