### ISSUE TITLE
binskim scans files one by one

### ISSUE THREAD

**Issue by fabio-s-franco** [microsoft/security-devops-azdevops#85]
There is no documentation and I couldn't find anything on the source code on how to customize the behavior of binskim.

The result is that it tries to scan files one by one, which makes the scan prohibitively slow (never succeeded to finish it).
If we can set the CLI argument through the extension, then it may be possible to use it.

**Comment by kewalaka** [comment]
hi @fabio-s-franco - I was just hitting the same wall myself.  I've found this documentation here which was helpful:

https://github.com/microsoft/security-devops-action/wiki#msdo-action-configuration

You can use a gdnconfig file & supply that to the defender for devops task, as the config option, from the above docs:

```
steps:
 - name: Run Microsoft Security DevOps Analysis
   uses: microsoft/security-devops-action@v1
   id: msdo
   with:
   # config: string. Optional. A file path to an MSDO configuration file ('*.gdnconfig').
   # policy: 'GitHub' | 'microsoft' | 'none'. Optional. The name of a well-known Microsoft policy. If no configuration file or list of tools is provided, the policy may instruct MSDO which tools to run. Default: GitHub.
   # categories: string. Optional. A comma-separated list of analyzer categories to run. Values: 'secrets', 'code', 'artifacts', 'IaC', 'containers. Example: 'IaC,secrets'. Defaults to all.
   # languages: string. Optional. A comma-separated list of languages to analyze. Example: 'javascript,typescript'. Defaults to all.
   # tools: string. Optional. A comma-separated list of analyzer tools to run. Values: 'bandit', 'binskim', 'eslint', 'templateanalyzer', 'terrascan', 'trivy'.
```

There's also a sample file for BinSkim options (and other tools) further on the same page:

https://github.com/microsoft/security-devops-action/wiki#binskim-gdnconfig-sample

I couldn't find this on Learn with the other pipeline yaml definitions, that would have made the search easier.
